{% set name = "msbuild-project-tools-server" %}
{% set version = "0.6.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/tintoy/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e6c3015957214b57af0a85617a41f421036eabad0b13a3ee3e2c014f40e4d357

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - {{ name }} &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/tintoy/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for MSBuild intellisense (including PackageReference completion).
  dev_url: https://github.com/tintoy/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
