{% set version = "0.7.0" %}

package:
  name: msbuild-project-tools-server
  version: {{ version }}

source:
  url: https://github.com/tintoy/msbuild-project-tools-server/archive/v{{ version }}.tar.gz
  sha256: e8ce1259d9953158ba06c6920b05e876a9502fa183cf2770aab278ee0af1ce7f

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - msbuild-project-tools-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/tintoy/msbuild-project-tools-server
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for MSBuild intellisense (including PackageReference completion).
  dev_url: https://github.com/tintoy/msbuild-project-tools-server

extra:
  recipe-maintainers:
    - danielnachun
